version: '3.4'
services:
  prysm-beacon-chain.public.dappnode.eth:
    image: 'prysm-beacon-chain.public.dappnode.eth:1.0.6'
    build:
      context: ./build
      args:
        - VERSION
    volumes:
      - 'data:/data'
    ports:
      - '4000:4000'
    restart: always
    environment:
      - 'WEB3PROVIDER=wss://goerli.prylabs.net/websocket'
      - EXTRA_OPTS
volumes:
  data: {}
