version: '3.4'
services:
  prysm-onyx-beacon-chain.dnp.dappnode.eth:
    image: 'prysm-onyx-beacon-chain.dnp.dappnode.eth:1.0.5'
    build:
      context: ./build
      args:
        - VERSION
    volumes:
      - 'data:/data'
    ports:
      - '13000'
    restart: always
    environment:
      - 'HTTP_WEB3PROVIDER=http://goerli-geth.dappnode:8545'
      - EXTRA_OPTS
volumes:
  data: {}
