version: '3.4'
services:
  prysm-onyx-beacon-chain.dnp.dappnode.eth:
    image: 'prysm-onyx-beacon-chain.dnp.dappnode.eth:1.0.12'
    build:
      context: ./build
      args:
        - VERSION
    volumes:
      - 'data:/data'
    ports:
      - '13000'
    restart: always
    environment:
      - 'WEB3PROVIDER=ws://goerli-geth.dappnode:8546'
      - EXTRA_OPTS
volumes:
  data: {}
